dist: trusty
sudo: false
language: c

addons:
  apt:
    packages:
      - check
      - doxygen
      - python3
      - python3.4-venv
      - python3-pip
      - lcov

script:
  - ./autogen.sh
  - mkdir build
  - cd build
  - ../configure --enable-code-coverage --disable-daemon
  - make
  - make check

after_success:
  # upload code coverage data
  - bash <(curl -s https://codecov.io/bash)
