dist: trusty
sudo: false
language: c

addons:
  apt:
    packages:
      - check
      - doxygen
      - python3
      - python3.4-venv
      - python3-pip
      - lcov
      - valgrind
      - libzmq3-dev
      - libzmq3-dbg
      - libczmq-dev
      - libczmq-dbg

script:
  - ./autogen.sh
  - mkdir build
  - cd build
  - ../configure --enable-code-coverage --disable-daemon --enable-debug
  - make
  - make check
  - make check-valgrind

after_success:
  # upload code coverage data
  - bash <(curl -s https://codecov.io/bash)

